name: HL Perps Snapshot → Dune (keyless)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "20 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip requests pandas

      - name: Show repo tree (debug)
        run: |
          pwd
          ls -la
          echo "----"
          ls -la src || true
          ls -la etl || true

      - name: Run ETL
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          DUNE_TABLE_NAME: hl_perps_daily
        run: |
          python src/hl_perps_snapshot_to_dune.py
