# .github/workflows/hl_perps.yml
name: Hyperliquid Perps → Dune (free API)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 * * * *"   # hourly at :17

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run ETL
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
          DUNE_TABLE_NAME: hyperliquid_perps_daily
        run: |
          python src/hyperliquid_perps_to_dune.py